-- 1. Create Tablespaces
CREATE TABLESPACE BASIC_DATA
           DATAFILE 'D:\app\HYUK\oradata\basic\BASIC_DATA.DBF'
           SIZE 64M
           AUTOEXTEND ON
           NEXT 10M;
           
CREATE TABLESPACE BASIC_INDEX
           DATAFILE 'D:\app\HYUK\oradata\basic\BASIC_INDEX.DBF'
           SIZE 100M
           AUTOEXTEND ON
           NEXT 10M;


-- 2. Create & Grant User
CREATE USER BASIC IDENTIFIED BY BASIC DEFAULT TABLESPACE BASIC_DATA;
GRANT CONNECT, DBA, RESOURCE, CREATE TABLE TO BASIC;
--GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE ANY INDEX, CREATE ANY TABLE, DROP ANY TABLE, ALTER ANY INDEX, ALTER ANY TABLE, EXECUTE ANY PROCEDURE, CREATE PROCEDURE TO BASIC;

COMMIT;

-- 3. Create Tables
CONN BASIC/BASIC;

CREATE TABLE ZZT_BOARD
(
	B_NUM               NUMBER  NOT NULL ,
	P_NUM            	NUMBER  NULL ,
	IP_ADDRESS          VARCHAR2(100)  NULL ,
	TITLE           	VARCHAR2(20)  NULL ,
	CONTETNS           	VARCHAR2(1000)  NULL ,
	PASSWD             	VARCHAR2(50)  NULL ,
	CNT             	NUMBER   DEFAULT 0 NOT NULL,
	INPUTDATE          	DATE   DEFAULT SYSDATE NOT NULL
)
	TABLESPACE BASIC_DATA;

CREATE UNIQUE INDEX BOARD_PK ON ZZT_BOARD
(B_NUM  ASC)
	TABLESPACE BASIC_INDEX;

ALTER TABLE ZZT_BOARD
	ADD  PRIMARY KEY (B_NUM);

COMMENT ON TABLE ZZT_BOARD IS '게시판번호'; 
COMMENT ON COLUMN ZZT_BOARD.B_NUM IS '게시판번호';
COMMENT ON COLUMN ZZT_BOARD.P_NUM IS '부모게시글번호';
COMMENT ON COLUMN ZZT_BOARD.IP_ADDRESS IS '사용자IP';
COMMENT ON COLUMN ZZT_BOARD.TITLE IS '제목';
COMMENT ON COLUMN ZZT_BOARD.CONTETNS IS '내용';
COMMENT ON COLUMN ZZT_BOARD.PASSWD IS '비밀번호';
COMMENT ON COLUMN ZZT_BOARD.CNT IS '조회수';
COMMENT ON COLUMN ZZT_BOARD.INPUTDATE IS '입력일';

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (1, 1, '127.0.0.1', '제목1' ,'내용1', '', 0, SYSDATE);

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (2, 2, '127.0.0.1', '제목2' ,'내용2', '', 0, SYSDATE);

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (3, 2, '127.0.0.1', '제목3' ,'내용3', '', 0, SYSDATE);

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (4, 2, '127.0.0.1', '제목4' ,'내용4', '', 0, SYSDATE);

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (5, 2, '127.0.0.1', '제목5' ,'내용5', '', 0, SYSDATE);

INSERT INTO ZZT_BOARD (B_NUM, P_NUM, IP_ADDRESS, TITLE, CONTETNS, PASSWD, CNT, INPUTDATE)
VALUES (6, 1, '127.0.0.1', '제목6' ,'내용6', '', 0, SYSDATE);

commit;

CREATE SEQUENCE SEQ_ZZT_BOARD_IDX 
	START WITH 1 
	INCREMENT BY 1 
	NOMAXVALUE 
	NOCACHE;
